name: Build and Publish image to Docker Hub
on:
  [workfow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./ -t lyvanthien/exampleci-cd-workflow:latest
      - name: push image to docker hub
        run: 
          docker push lyvanthien/exampleci-cd-workflow:latest