# name: Build and Publish image to Docker Hub
# on:
  # push:
    # branches:
      # - main

# jobs:
  # publish_images:
    # runs-on: ubuntu-latest
    # steps: 
      # - name: checkout
      #   uses: actions/checkout@v4
      # - name: build image
      #   run: docker build ./ -t lyvanthien/exampleci-cd-workflow:latest
      # - name: push image to docker hub
      #   run: 
      #     docker push lyvanthien/exampleci-cd-workflow:latest

name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: build
          load: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest